#!/bin/sh
#
# @name Gazebo VPP quad (servo test)
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=vpp_quad}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.174
param set-default CA_ROTOR0_PY 0.174
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.174
param set-default CA_ROTOR1_PY -0.174
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.174
param set-default CA_ROTOR2_PY -0.174
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.174
param set-default CA_ROTOR3_PY 0.174
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.6
param set-default NAV_DLL_ACT 2

# Drag Specific Force:
param set-default EKF2_BCOEF_X 0.0
param set-default EKF2_BCOEF_Y 0.0
param set-default EKF2_MCOEF 0.12

# ---- VPP quad test overrides (later set-default calls win) ----
param set-default CA_AIRFRAME 20
param set-default COM_DISARM_PRFLT 0
param set-default COM_DISARM_LAND 0
param set-default CA_HELI_THR_C0 0
param set-default CA_HELI_THR_C1 0
param set-default CA_HELI_THR_C2 0
param set-default CA_HELI_THR_C3 0
param set-default CA_HELI_THR_C4 0
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
